INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10, 'Агроплощадь');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (520, 'Наковальня');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (522, 'Манекен портного');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (525, 'Поварской котел');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (532, 'Верстак');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (557, 'Плавильная печь');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (558, 'Плотницкий станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (560, 'Кожевенный стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (561, 'Ткацкий станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (564, 'Стол декоратора');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (566, 'Станок для акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (568, 'Алхимический стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (1918, 'Отличная наковальня');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (1972, 'Манекен кожевника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (2235, 'Отличный манекен бронника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (2236, 'Отличный манекен кожевника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (2237, 'Отличный манекен портного');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4221, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4223, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4224, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4225, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4226, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4228, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4234, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4235, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4236, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4237, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4240, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4241, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4243, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (4250, 'Отличный поварской котел');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (5218, 'Манекен бронника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (5598, 'Станок каменотеса');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6090, 'Консорциомат');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6311, 'Печатный станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6312, 'Пресс для бумаги');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6322, 'Место обмена снаряжения острова Миражей');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6454, 'Швейная машинка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6501, 'Стол ювелира');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6795, 'Алтарь Занданы');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6847, 'Алтарь Дауты');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (6986, 'Аппарат для продажи ярлыков Руру');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7005, 'Верстак колонистов');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7088, 'Походный верстак');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7118, 'Брошенный манекен');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7119, 'Брошенный манекен');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7121, 'Кузница драконьего пламени');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7193, 'Воскресная мастерская золотого короля');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7194, 'Мастерская для создания флага');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7402, 'Лавка наград за рейтинги');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7424, 'Жутковинская мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7701, 'Мастерская товаров общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (7702, 'Автомат по выдаче наград события Стань богаче');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8043, 'Манекен эрнардского портного');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8218, 'Верстак для творчества');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8295, 'Столик с напитками');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8414, 'Мастерская кристаллов маринита');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8465, 'Корабельный тигель');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8808, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9016, 'Автомат для обмена знаков синей луны');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9108, 'Домашняя клумба');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9153, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9187, 'Бурлящий котелок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9212, 'Книга с историями ноябрьской ночи');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9259, 'Лавка селекционеров моринги');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9298, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9307, 'Торговый склад');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9351, 'Мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (9404, 'Манекен шорника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10055, 'Кувшин с брагой');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10129, 'Жила изначального акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10137, 'Мастерская фейерверков');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10214, 'Станок для акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10532, 'Аппарат обмена массивных сундуков');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10556, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (10570, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11104, 'Мастерская костюмов судьи секты');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11243, 'Замковая мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11247, 'Мастерская правителя союза');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11400, 'Верстак Даэльмина');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11414, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11701, 'Многофункциональная мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11729, 'Лавка региональной общины Кладбища драконов');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11732, 'Мастерская лавочника дома региональной общины Белого леса');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11767, 'Лавка региональной общины Древнего леса');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (11785, 'Лавка региональной общины Долины цветущих прудов');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12143, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12180, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12187, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12191, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12193, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12196, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12199, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12200, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12201, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12202, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12204, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12206, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12207, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12291, 'Мастерская товаров Щ.И.Т.а');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12297, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12326, 'Эфенский алтарь');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12416, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12417, 'Верстак Ганса');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12455, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12611, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12654, 'Упаковочный стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12665, 'Верстак Ман Ли');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12676, 'Плавильная печь консорциума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12677, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12766, 'Стол кондитера');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12810, 'Мастерская для починки ханбока');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12885, 'Мастерская шоколатье');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (12936, 'Избирательная машина');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13005, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13006, 'Мастерская зелий');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13007, 'Мастерская фруктовых напитков');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13014, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13028, 'Угольная мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13066, 'Поварской стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13067, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13128, 'Стол скотовода');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13228, 'Фестивальная лавка Джейка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13229, 'Лотерея Джейка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13370, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13384, 'Анимагический источник');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13419, 'Оружейный барон');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13497, 'Разделочный стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13748, 'Жила изначального акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13768, 'Жила изначального акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13769, 'Жила изначального акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (13870, 'Трудовое свидетельство для крепостных сооружений');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (22397, 'Отличный верстак');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (22417, 'Отличный алхимический стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (23927, 'Табличка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42207, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42278, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42308, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42318, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42328, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42338, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42386, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42397, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42425, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42449, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42455, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42466, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (54257, 'Станок нумизмата');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (60786, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (68726, 'Отличный печатный станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (69266, 'Верстак Миража');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (72856, 'Станок скульптора');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (74316, 'Отличный консорциомат');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (74426, 'Место продажи предметов Хеллоуина');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (74876, 'Место обмена древних реликвий');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (79818, 'Кухонная посуда для новогодней вечеринки');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (79828, 'Мастерская саженцев акхиумного дерева');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (80674, 'Ингредиенты книги рецептов ремесленника');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (82094, 'Аппарат обмена сердец на акиум');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (82108, 'Обмен ключей богини');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (86714, 'Верстак корабела');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (87158, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (87178, 'Верстак бондаря');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (87758, 'Обменник пиратских ваучеров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (89208, 'Котел для приготовления пудинга');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (89218, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (90928, 'Жутковинская мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (90984, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (91098, 'Верстак для обработки материалов');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (91108, 'Разделочный стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (91318, 'Лаборатория');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (91328, 'Подарочный сундук торговца ирисками');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (91578, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (92578, 'Таинственная жеода');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (94308, 'Наковальня из руин древней крепости');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (98238, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (101318, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (101328, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (101348, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (102098, 'Тигель стихий');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (103418, 'Станок для акхиума');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (104358, 'Мастерская знаков участников гильдии');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (104688, 'Отличный поварской котел');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (105548, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (105558, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (105578, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (106458, 'Мастерская скульптора');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (107317, 'Иферийский тигель стихий');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (108677, 'Лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (108857, 'Поварской котел');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (109167, 'Печатный станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (109307, 'Телега для обмена подарков принцессы');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (109647, 'Ведерко красной соли');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (109667, 'Разделочный стол');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (110497, 'Мастерская региональных товаров Изначального материка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (110657, 'Мастерская костюмов судьи секты');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (112447, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (115584, 'Пошлина леса Гвинедар');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (116967, 'Многофункциональная мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (117117, 'Лавка региональной общины леса Гвинедар');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (117317, 'Мастерская лавочника дома региональной общины Двух Корон');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (117627, 'Мастерская лавочника дома региональной общины руин Харихараллы');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (117667, 'Мастерская лавочника дома региональной общины Хазиры');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (117877, 'Лавка региональной общины Долины талых снегов');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (118797, 'Лавка региональной общины Поющей земли');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (120187, 'Многофункциональная мастерская региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121047, 'Мастерская небесных стражей');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121427, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121457, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121477, 'Стол для обмена урожая');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121757, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121817, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121827, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121837, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121847, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121857, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121867, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121887, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121897, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121907, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121927, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121947, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121957, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121977, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (121983, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122031, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122053, 'Мастерская товаров региональной общины');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122493, 'Сундук для обмена сладких подарков');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122501, 'Мастерская букетчика');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122511, 'Универсальный генератор плазмы в Мираже');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122793, 'Мастерская сладостей');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (122903, 'Мастерская товаров Щ.И.Т.а');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (130228, 'Мастерская товаров Щ.И.Т.а');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (130238, 'Мастерская товаров Щ.И.Т.а');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (139748, 'Праздничная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (224001, 'Отличный стол декоратора');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (644301, 'Домница');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000017, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000039, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000130, 'Фабричный станок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000144, 'Ведьмин котелок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000189, 'Королевская лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000248, 'Мастерская Диона');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000252, 'Временная мастерская');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (8000253, 'Мастерская трактирщицы Мальмы');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (42290004, 'Мастерская региональных товаров');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (80001717, 'Фестивальная лавка');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (80002398, 'Чугунный котелок');
INSERT INTO `doods`(`dood_id`, `dood_name`) VALUES (80002517, 'Артельная мастерская');
