INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (1, 'Оружие', 1, 'Мечи, луки, копья, посохи, щиты и т.д.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (2, 'Доспехи', 1, 'Все виды доспехов - от легких до тяжелых.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (3, 'Украшения', 1, 'Серьги, ожерелья и кольца.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (4, 'Костюмы', 1, 'Одежда, не обладающая боевыми\nи защитными характеристиками.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (5, 'Зелья', 1, 'Расходуемые предметы: зелья, пища, рецепты и т.д.', 4);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (6, 'Ремесло', 1, 'Обработанные ремесленные материалы.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (7, 'Задания', 1, 'Предметы, необходимые для выполнения заданий.', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (8, 'Транспорт', 1, 'Лошади и львы, корабли и глайдеры -\nвсе, на чем можно путешествовать.', 2);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (9, 'Сбруя', 1, 'Снаряжение для питомцев.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (10, 'Книги', 1, '', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (11, 'Ящики', 1, '', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (12, 'Чертежи', 1, 'Ремесленные чертежи и схемы.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (13, 'Семена и саженцы', 1, 'Саженцы и семена.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (14, 'Животные', 1, 'Куры, гуси, цыплята, козлята и прочие животные,\nкоторых можно выращивать на фермах.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (15, 'Мебель', 1, 'Мебель, предметы декора и прочие вещи для дома.', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (16, 'Двор', 0, '', NULL);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (17, 'Мелочи', 1, 'Игрушки, реликвии и прочие милые мелочи.', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (18, 'Прочее', 1, 'Предметы, не входящие ни в одну\nиз предложенных категорий.', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (19, ' -', 0, '', NULL);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (20, 'Груз', 1, '', NULL);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (21, 'Экзотика', 0, '', NULL);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (22, 'Самоцветы', 1, 'Драгоценные камни и предметы\nдля улучшения снаряжения.', NULL);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (23, 'Сырье', 1, 'Необработанные ресурсы: древесина, руда, камни и т.п.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (24, 'Запчасти', 1, 'Детали для изготовления машин и глайдеров.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (25, 'Улики', 1, '', 6);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (26, 'Акхиум', 0, 'Все виды акхиума - от порошков до эссенций.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (27, 'Монеты', 1, 'Старинные монеты: дельфийские звезды и т.д.', 3);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (28, 'Питомцы', 1, 'Питомцы', 2);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (29, 'Снасти', 1, 'Предметы, необходимые для рыбалки.', 1);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (30, 'Расходка', 1, 'Расходуемые предметы', 4);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (31, 'Для ГС', 1, 'Предметы для улучшения эквипа', 5);
INSERT INTO `item_groups`(`id`, `name`, `visible_ui`, `description`, `sgr_id`) VALUES (32, 'Системные', 0, 'Системная категория для моих сервисов', NULL);
