INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (1, 'Прочее', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (2, 'Универсальный костюм', 4);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (4, 'Судно', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (5, 'Фамильяр', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (6, 'Здание', 12);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (7, 'Предмет интерьера', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (8, 'Саженец', 13);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (10, 'Костюм', 4);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (12, 'Микстура', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (13, 'Пища', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (14, 'Ремесленный предмет', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (15, 'Осадное орудие', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (17, 'Бумага', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (18, 'Книга', 10);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (19, 'Нипанятна', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (20, 'Лунная руна', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (21, 'Детеныш', 14);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (23, 'Слиток металла', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (24, 'Древесина', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (25, 'Камень', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (26, 'Кожа', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (27, 'Ткань', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (28, 'Запчасть', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (30, 'Флакон', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (31, 'Инструмент геральдиста', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (32, 'Акхиум', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (33, 'Краситель', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (34, 'Реагент', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (35, 'Действие', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (36, 'Пищевое масло', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (37, 'Приправа', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (38, 'Руда', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (39, 'Дерево', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (40, 'Камень', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (41, 'Сырье', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (42, 'Волокно', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (43, 'Деталь', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (44, 'Доказательство', 25);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (45, 'Мясо', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (46, 'Дары моря', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (47, 'Зерно', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (48, 'Овощ', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (49, 'Плод', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (51, 'Семена', 13);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (52, 'Специя', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (53, 'Алхимический ингредиент', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (55, 'Цветок', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (56, 'Удобрение', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (58, 'Драгоценный металл', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (59, 'Самоцвет', 23);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (62, 'Реактив', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (64, 'Задание', 7);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (65, 'Рецепт', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (69, 'Кинжал', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (70, 'Одноручный меч', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (71, 'TEST_Quest Equip : Weapon', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (72, 'Одноручный клинок', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (73, 'Одноручный топор', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (74, 'Одноручное дробящее', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (75, 'Одноручный посох', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (76, 'Одноручное древковое', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (77, 'Лук', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (78, 'Метательное оружие', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (79, 'Щит', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (80, 'Струнный инструмент', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (81, 'Духовой инструмент', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (82, 'Ударный инструмент', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (83, 'Легкий доспех', 2);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (84, 'Средний доспех', 2);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (85, 'Тяжелый доспех', 2);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (86, 'Ожерелье', 3);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (87, 'Кольцо', 3);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (88, 'Украшения', 3);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (89, 'Экстерьер', 16);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (90, 'Мебель', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (92, 'Ездовой питомец', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (93, 'Транспорт', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (94, 'Ящик', 11);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (96, 'TEST_NPC Packs', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (97, 'Напиток', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (98, 'TEST_Trash : Craft', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (99, 'Бесполезный предмет', 17);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (100, 'Водный питомец', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (101, 'Крылья', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (102, 'Питомец-компаньон', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (103, 'TEST_Trash : Material', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (104, 'TEST_Trash : Doodad', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (105, 'TEST_Trash : Consume', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (106, 'Ключ', 7);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (107, 'Необычный предмет', 7);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (108, 'Снаряжение питомца', 9);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (109, 'Питомец', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (110, 'Мелочи', 17);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (111, 'TEST_Quest Equip : Accessory', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (113, 'Магический эликсир', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (114, 'Защитный эликсир', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (115, 'Целебная микстура', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (116, 'Целебный эликсир', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (117, 'Разное', 17);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (118, 'Глайдер', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (119, 'Редкий материал', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (120, 'Магический предмет', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (121, 'Плащ', 2);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (122, 'Груз', 20);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (125, 'Серьга', 3);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (126, 'Бесполезная находка', 17);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (127, 'Двуручный меч', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (128, 'Двуручный клинок', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (129, 'Двуручный топор', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (130, 'Двуручное дробящее', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (131, 'Двуручный посох', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (132, 'Двуручное древковое', 1);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (133, 'Региональный товар', 20);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (134, 'Историческая находка', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (135, 'TEST_Drop Equip : Armor', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (136, 'TEST_Drop Equip : Accessory', 19);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (137, 'Ездовой питомец', 8);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (138, 'Монета', 27);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (139, 'Боевой питомец', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (140, 'Предмет осады', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (141, 'Шеврон', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (142, 'Боевой питомец', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (143, 'Снаряд', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (144, 'Питомец', 28);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (145, 'Удочка', 29);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (146, 'Чучело', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (147, 'Гравюра', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (148, 'Ноты', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (149, 'Свиток(расходный)', 30);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (150, 'Фантастический волшебный товар', 5);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (151, 'Свиток(для ГС)', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (152, 'Гравировка', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (153, 'Неопознанный предмет', 18);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (156, 'Снаряжение для заводной игрушки', 9);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (157, 'Корабельная артиллерия', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (158, 'Рулевое устройство', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (159, 'Мачта', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (160, 'Парус', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (161, 'Корабельное освещение', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (162, 'Трап', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (164, 'Поисковое оборудование', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (165, 'Дополнительное оборудование', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (166, 'Носовая фигура', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (167, 'Грузовое оборудование', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (169, 'Судовой колокол', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (170, 'Ускорители', 24);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (171, 'Товары фактории', 20);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (172, 'Расчетные', 32);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (173, 'Валюта', 32);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (174, 'Огород', 13);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (175, 'Хранилище', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (176, 'Свиток пробуждения', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (177, 'Материал для синтеза', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (178, 'Садовое украшение', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (179, 'Ремесленное приспособление', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (180, 'Комнатный питомец', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (181, 'Декоративный предмет интерьера', 15);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (182, 'Выдает задание', 7);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (183, 'Алхимия', 6);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (184, 'Стекло, глазурь', 31);
INSERT INTO `item_categories`(`id`, `name`, `item_group`) VALUES (185, 'Магический предмет (р)', 30);
