INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Дары Белого леса', 'Белый лес', 'Обычный', '18');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Сладкие хлебцы Белого леса', 'Белый лес', 'Обычный', '18');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Фаршированные тыквы', 'Белый лес', 'Ротонда', '18');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Луковые колечки', 'Лес Гвинедар', 'Ротонда', '1');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Перо гвинедарского гуся', 'Лес Гвинедар', 'Обычный', '1');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Пироги со сладкой начинкой', 'Лес Гвинедар', 'Обычный', '1');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Вяленые припасы Заболоченных низин', 'Заболоченные низины', 'Обычный', '26');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Грибница Заболоченных низин', 'Заболоченные низины', 'Обычный', '26');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Арахисовое масло', 'Заболоченные низины', 'Ротонда', '26');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Золотистые дорожные галеты', 'Золотые равнины', 'Обычный', '22');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Сушеный батат Золотых равнин', 'Золотые равнины', 'Обычный', '22');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Комбикорм Золотых равнин', 'Золотые равнины', 'Ротонда', '22');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Бледно-желтый краситель', 'Земля говорящих камней', 'Обычный', '3');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Плотный войлок', 'Земля говорящих камней', 'Обычный', '3');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Разноцветные краски', 'Земля говорящих камней', 'Ротонда', '3');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Печенье Двух Корон', 'Две короны', 'Обычный', '8');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Целебная мазь', 'Две короны', 'Обычный', '8');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Травяной сбор Двух Корон', 'Две короны', 'Ротонда', '8');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Мазь от солнечных ожогов', 'Долгая коса', 'Обычный', '27');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Пряное мясо Долгой косы', 'Долгая коса', 'Обычный', '27');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Перченые огурчики', 'Долгая коса', 'Ротонда', '27');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Душистое мыло', 'Холмы лилиот', 'Обычный', '6');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Цветочное масло для светильников', 'Холмы лилиот', 'Обычный', '6');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Ячменная брага', 'Холмы лилиот', 'Ротонда', '6');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Ароматная набивка для подушек', 'Мэрианхольд', 'Обычный', '2');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Моченая вишня', 'Мэрианхольд', 'Обычный', '2');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Средство от мозолей', 'Мэрианхольд', 'Ротонда', '2');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Лимонный уксус', 'Полуостров падающих звезд', 'Обычный', '20');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Пряности Западного материка', 'Полуостров падающих звезд', 'Обычный', '20');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Цветочные леденцы', 'Полуостров падающих звезд', 'Ротонда', '20');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Вяленые припасы Солрида', 'Полуостров Солрид', 'Обычный', '5');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Провиант для путешественников', 'Полуостров Солрид', 'Обычный', '5');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Солридский клубничный джем', 'Полуостров Солрид', 'Ротонда', '5');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Апельсиновый джем', 'Инистра', 'Обычный', '17');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Ароматические подушечки', 'Поющая земля', 'Обычный', '12');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Ароматная древесина Махадеби', 'Махадеби', 'Обычный', '9');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Ароматный чай', 'Хазира', 'Ротонда', '23');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Банановое повидло', 'Махадеби', 'Обычный', '9');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Букеты роз', 'Инистра', 'Ротонда', '17');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Виноградный джем', 'Тигриный хребет', 'Обычный', '24');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Вяленые припасы Саванны', 'Саванна', 'Обычный', '29');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Вяленые припасы Хазиры', 'Хазира', 'Обычный', '23');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Вяленые припасы Харихараллы', 'Руины Харихараллы', 'Ротонда', '15');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Компост', 'Плато соколиной охоты', 'Ротонда', '11');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Кукурузная мука', 'Рокочущие перевалы', 'Ротонда', '16');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Маринованные яйца', 'Радужные пески', 'Обычный', '7');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Мятные леденцы', 'Саванна', 'Обычный', '29');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Набивка для тюфяка', 'Плато соколиной охоты', 'Обычный', '11');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Настойка алоэ', 'Саванна', 'Ротонда', '29');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Оливковое масло', 'Инистра', 'Обычный', '17');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Притирания для кожи', 'Полуостров рассвета', 'Обычный', '4');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Пряности Харихараллы', 'Руины Харихараллы', 'Обычный', '15');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Пуховки для лица', 'Полуостров рассвета', 'Обычный', '4');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Рисовая лапша', 'Поющая земля', 'Ротонда', '12');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Сладкий картофель', 'Руины Харихараллы', 'Обычный', '15');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Смесь специй для вина', 'Древний лес', 'Обычный', '25');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Соленые огурчики', 'Махадеби', 'Ротонда', '9');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Сушеные семечки', 'Радужные пески', 'Ротонда', '7');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Сушеный инжир', 'Рокочущие перевалы', 'Обычный', '16');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Терпкое вишневое вино', 'Поющая земля', 'Обычный', '12');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Толченая куркума', 'Радужные пески', 'Обычный', '7');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Толченый шафран', 'Полуостров рассвета', 'Ротонда', '4');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Фаршированные помидоры', 'Тигриный хребет', 'Ротонда', '24');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Фруктовое молоко', 'Древний лес', 'Обычный', '25');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Фруктовое печенье', 'Рокочущие перевалы', 'Обычный', '16');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Хазирские лечебные перины', 'Хазира', 'Обычный', '23');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Хрустящие лепешки', 'Тигриный хребет', 'Обычный', '24');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Чесночная приправа', 'Древний лес', 'Ротонда', '25');
INSERT INTO `pack_zones`(`pack_name`, `zone_name`, `pack_type`, `zone_id`) VALUES ('Яблочные оладьи', 'Плато соколиной охоты', 'Обычный', '11');
