INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (1, 'Инженерное дело', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (2, 'Кузнечное дело', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (3, 'Особые мастерские', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (4, 'Обработка древесины', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (5, 'Торговля', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (6, 'Строительство', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (7, 'Исследование', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (8, 'Ремесло декоратора', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (9, 'Обработка камня', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (10, 'Кожевничество', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (11, 'Алхимия', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (12, 'Особые предметы', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (13, 'Изящные искусства', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (14, 'Портняжное дело', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (15, 'Книгопечатание', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (16, 'Оружейное дело', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (17, 'Мираж', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (18, 'Травничество', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (19, 'Земледелие', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (20, 'Животноводство', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (21, 'Кулинария', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (22, 'Подземелья', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (23, 'Заготовка древесины', 1);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (24, 'Сбруя', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (25, 'Прочее', 0);
INSERT INTO `profs`(`prof_id`, `profession`, `used`) VALUES (26, 'Рыбная ловля', 1);
