INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4856, 'Саженец', 'Саженец яблони', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4857, 'Саженец', 'Саженец дуба', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4858, 'Саженец', 'Саженец ясеня', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4859, 'Саженец', 'Саженец ивы', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4860, 'Саженец', 'Саженец граба', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4861, 'Саженец', 'Саженец оливы', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4862, 'Саженец', 'Саженец пробкового дуба', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4863, 'Саженец', 'Саженец белой осины', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4864, 'Саженец', 'Саженец березы', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4865, 'Саженец', 'Саженец винограда', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4866, 'Саженец', 'Саженец тополя', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4889, 'Семена', 'Семена черники', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (4904, 'Семена', 'Семена хлопка', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13724, 'Саженец', 'Саженец лимона', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13725, 'Саженец', 'Саженец смоковницы', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13726, 'Саженец', 'Саженец лаврового дерева', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13727, 'Саженец', 'Саженец кокосовой пальмы', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13728, 'Саженец', 'Саженец гевеи', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13729, 'Саженец', 'Саженец финиковой пальмы', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (13731, 'Саженец', 'Саженец кипариса', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14894, 'Саженец', 'Саженец камфорного дерева', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14895, 'Саженец', 'Саженец бамбука', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14896, 'Саженец', 'Саженец эбенового дерева', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14897, 'Саженец', 'Саженец каштана', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14898, 'Саженец', 'Саженец сосны', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14899, 'Саженец', 'Саженец ели', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14900, 'Саженец', 'Саженец можжевельника', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14901, 'Саженец', 'Саженец белокорой пихты', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14902, 'Саженец', 'Саженец криптомерии', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14903, 'Саженец', 'Саженец тиса', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14904, 'Саженец', 'Саженец граната', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14905, 'Саженец', 'Саженец бука', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14906, 'Саженец', 'Саженец вишни', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14907, 'Саженец', 'Саженец абрикоса', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14908, 'Саженец', 'Саженец апельсина', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14910, 'Саженец', 'Саженец моринги', 650);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (14911, 'Саженец', 'Саженец баобаба', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15646, 'Семена', 'Зерна риса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15647, 'Семена', 'Зерна овса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15648, 'Семена', 'Зерна проса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15650, 'Семена', 'Зерна чумизы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15651, 'Семена', 'Зерна пшеницы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15652, 'Семена', 'Зерна ячменя', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15653, 'Семена', 'Зерна кукурузы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15654, 'Семена', 'Семена бобов', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15655, 'Семена', 'Ржаное зерно', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15656, 'Семена', 'Семена арахиса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15657, 'Семена', 'Семена клубники', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15659, 'Семена', 'Семена картофеля', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15660, 'Семена', 'Семена батата', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15661, 'Семена', 'Семена моркови', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15662, 'Семена', 'Семена чеснока', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15663, 'Семена', 'Семена лука', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15664, 'Семена', 'Семена огурцов', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15665, 'Семена', 'Семена помидоров', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15666, 'Семена', 'Семена тыквы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15667, 'Семена', 'Семена лаванды', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15668, 'Семена', 'Семена розмарина', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15669, 'Семена', 'Семена василька', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15670, 'Семена', 'Семена лилии', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15671, 'Семена', 'Семена подсолнуха', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15672, 'Семена', 'Семена кактуса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15673, 'Семена', 'Семена нарцисса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15674, 'Семена', 'Семена лотоса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15675, 'Семена', 'Семена азалии', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15676, 'Семена', 'Семена клевера', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15677, 'Семена', 'Семена розы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15678, 'Семена', 'Семена аира благовонного', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15680, 'Семена', 'Семена мака', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (15682, 'Семена', 'Семена мяты', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16225, 'Детеныш', 'Теленок', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16226, 'Детеныш', 'Ягненок', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16229, 'Детеныш', 'Поросенок', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16230, 'Детеныш', 'Цыпленок', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16264, 'Семена', 'Семена сансевьеры', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16269, 'Семена', 'Семена куркумы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16270, 'Семена', 'Семена ванили', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16271, 'Семена', 'Семена черного перца', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16272, 'Семена', 'Семена шафрана', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16277, 'Семена', 'Семена перца', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16279, 'Семена', 'Семена алоэ', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16282, 'Семена', 'Семена чертополоха', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16283, 'Семена', 'Споры кордицепса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16285, 'Семена', 'Семена сансама', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16294, 'Семена', 'Семена женьшеня', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16332, 'Саженец', 'Саженец гинкго', 600);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16333, 'Саженец', 'Саженец юкки', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16334, 'Саженец', 'Саженец клена', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16335, 'Саженец', 'Саженец лиственницы', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16336, 'Саженец', 'Саженец пихты', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16337, 'Саженец', 'Саженец секвойи', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16338, 'Саженец', 'Саженец банана', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16339, 'Саженец', 'Саженец авокадо', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (16340, 'Саженец', 'Саженец какао', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (17261, 'Семена', 'Грибные споры', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (17711, 'Семена', 'Блестящие семена горной жилы', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18441, 'Саженец', 'Засохший саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18751, 'Семена', 'Семена пепельного кустарника', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18752, 'Саженец', 'Саженцы пылающего дерева', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18823, 'Саженец', 'Розовый ажурный коралл', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18824, 'Саженец', 'Зеленый ажурный коралл', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18825, 'Семена', 'Споры бурых водорослей', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18826, 'Семена', 'Споры желто-зеленых водорослей', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18827, 'Саженец', 'Оранжевый гладкий коралл', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18829, 'Саженец', 'Древовидный коралл', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18830, 'Саженец', 'Малая жемчужница', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18831, 'Саженец', 'Белый шаровидный коралл', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (18832, 'Саженец', 'Голубой шаровидный коралл', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (19939, 'Детеныш', 'Утенок', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (19940, 'Детеныш', 'Гусенок', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (19941, 'Детеныш', 'Индюшонок', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (19942, 'Детеныш', 'Козленок', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (19943, 'Детеныш', 'Детеныш буйвола', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (23635, 'Семена', 'Семена корнеплода', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26377, 'Семена', 'Пакет семян картофеля', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26378, 'Семена', 'Пакет семян огурца', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26430, 'Саженец', 'Саженец веерной пальмы', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26431, 'Саженец', 'Саженец осины', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26449, 'Семена', 'Пакет семян моркови', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26450, 'Семена', 'Пакет семян лука', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26451, 'Семена', 'Пакет семян чеснока', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26452, 'Семена', 'Пакет зерен ячменя', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26453, 'Семена', 'Пакет зерен риса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26454, 'Семена', 'Пакет зерен проса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26455, 'Семена', 'Пакет зерен кукурузы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26456, 'Семена', 'Пакет зерен пшеницы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26458, 'Семена', 'Пакет семян клевера', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26459, 'Семена', 'Пакет семян азалии', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26460, 'Семена', 'Пакет семян нарцисса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26461, 'Семена', 'Пакет семян розы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26462, 'Семена', 'Пакет семян хлопка', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26463, 'Семена', 'Пакет семян лилии', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26464, 'Семена', 'Пакет семян лотоса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26465, 'Семена', 'Пакет семян василька', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26466, 'Семена', 'Пакет семян аира благовонного', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26467, 'Семена', 'Пакет семян лаванды', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26468, 'Семена', 'Пакет семян мяты', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26469, 'Семена', 'Пакет семян розмарина', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26470, 'Семена', 'Пакет грибных спор', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26471, 'Семена', 'Пакет семян чертополоха', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26638, 'Детеныш', 'Детеныш тигровой ятты', 450);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26821, 'Детеныш', 'Бамбуковый загон для кур', 650);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (26956, 'Саженец', 'Саженец грозового акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (28125, 'Детеныш', 'Белый медвежонок', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30288, 'Семена', 'Пакет семян помидора', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30289, 'Семена', 'Пакет семян клубники', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30290, 'Семена', 'Пакет семян тыквы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30291, 'Семена', 'Пакет семян батата', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30293, 'Семена', 'Пакет зерен ржи', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30294, 'Семена', 'Пакет семян арахиса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30295, 'Семена', 'Пакет семян бобов', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30296, 'Семена', 'Пакет зерен чумизы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30297, 'Семена', 'Пакет семян кактуса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30298, 'Семена', 'Пакет семян сансевьеры', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30299, 'Семена', 'Пакет семян подсолнуха', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30300, 'Семена', 'Пакет семян куркумы', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30301, 'Семена', 'Пакет семян мака', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30302, 'Семена', 'Пакет семян шафрана', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30303, 'Семена', 'Пакет семян алоэ', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30304, 'Семена', 'Пакет семян женьшеня', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30506, 'Детеныш', 'Ромашка', 1200);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30515, 'Саженец', 'Призовая секвойя', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (30516, 'Семена', 'Призовая рисовая делянка', 1200);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31813, 'Семена', 'Семена занданита', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31814, 'Семена', 'Семена дыбоборода', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31815, 'Семена', 'Семена лисохвоста', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31816, 'Семена', 'Семена перистого папоротника', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31817, 'Семена', 'Семена колючего папоротника', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (31818, 'Семена', 'Семена щетинника', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32928, 'Саженец', 'Пакет саженцев гевеи', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32929, 'Саженец', 'Пакет саженцев белой осины', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32930, 'Саженец', 'Пакет саженцев клена', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32931, 'Саженец', 'Пакет саженцев бамбука', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32932, 'Саженец', 'Пакет саженцев сосны', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32933, 'Детеныш', 'Бамбуковый загон для уток', 650);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32934, 'Детеныш', 'Бамбуковый загон для гусей', 650);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32935, 'Детеныш', 'Крытое стойло для овец', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32936, 'Детеныш', 'Крытое стойло для коз', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32937, 'Детеныш', 'Крытое стойло для коров', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32938, 'Детеныш', 'Крытое стойло для ятт', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (32939, 'Детеныш', 'Крытый загон для белых медведей', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34296, 'Семена', 'Экспериментальная грядка с семенами тыквы', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34310, 'Семена', 'Экспериментальная клумба с семенами подсолнуха', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34311, 'Детеныш', 'Экспериментальный инкубатор с утиными яйцами', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34312, 'Саженец', 'Экспериментальная клумба с саженцем сосны', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34321, 'Саженец', 'Спутанный саженец дерева', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34351, 'Семена', 'Пакет таинственных семян', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34919, 'Саженец', 'Хвойная рощица', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34920, 'Саженец', 'Тропическая рощица', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34921, 'Саженец', 'Плодовая рощица', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34923, 'Огород', 'Аптекарский огород', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34924, 'Огород', 'Цветник', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34925, 'Семена', 'Злаковая делянка', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34926, 'Огород', 'Грядка с пряными травами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34927, 'Семена', 'Овощная грядка', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (34931, 'Детеныш', 'Птичий дворик', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35065, 'Саженец', 'Призовая секвойя', 1200);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35185, 'Семена', 'Парник с картофелем', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35186, 'Семена', 'Парник с огурцами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35187, 'Семена', 'Парник с морковью', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35188, 'Семена', 'Парник с луком', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35189, 'Семена', 'Парник с помидорами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35190, 'Семена', 'Парник с чесноком', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35191, 'Семена', 'Парник с клубникой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35192, 'Семена', 'Парник с тыквой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35193, 'Семена', 'Парник с бататом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35194, 'Семена', 'Парник с перцем', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35195, 'Семена', 'Парник с ячменем', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35196, 'Семена', 'Парник с рисом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35197, 'Семена', 'Парник с кукурузой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35198, 'Семена', 'Парник с пшеницей', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35199, 'Семена', 'Парник с овсом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35200, 'Семена', 'Парник с рожью', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35201, 'Семена', 'Парник с арахисом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35202, 'Семена', 'Парник с бобами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35203, 'Семена', 'Парник с просом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35204, 'Семена', 'Парник с клевером', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35205, 'Семена', 'Парник с азалиями', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35206, 'Семена', 'Парник с нарциссами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35207, 'Семена', 'Парник с розами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35208, 'Семена', 'Парник с хлопком', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35209, 'Семена', 'Парник с лилиями', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35210, 'Семена', 'Парник с лотосами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35211, 'Семена', 'Парник с васильками', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35212, 'Семена', 'Парник с кактусами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35213, 'Семена', 'Парник с аиром', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35214, 'Семена', 'Парник с лавандой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35215, 'Семена', 'Парник с мятой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35216, 'Семена', 'Парник с розмарином', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35217, 'Семена', 'Парник с подсолнухами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35218, 'Семена', 'Парник с куркумой', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35219, 'Семена', 'Парник с маками', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35220, 'Семена', 'Парник с шафраном', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35221, 'Семена', 'Парник с грибами', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35222, 'Семена', 'Парник с чертополохом', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35223, 'Семена', 'Парник с алоэ', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35224, 'Семена', 'Парник с женьшенем', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35244, 'Саженец', 'Экспериментальная клумба с саженцем сосны', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35245, 'Семена', 'Экспериментальная грядка с семенами тыквы', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35246, 'Семена', 'Экспериментальная клумба с семенами подсолнуха', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35247, 'Детеныш', 'Экспериментальный инкубатор с утиными яйцами', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35301, 'Саженец', 'Сортовой саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (35728, 'Саженец', 'Гигантская призовая секвойя', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (36485, 'Семена', 'Семена красного бальзамина', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (36486, 'Семена', 'Семена оранжевого бальзамина', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (36487, 'Семена', 'Семена розового бальзамина', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (36541, 'Саженец', 'Политый сортовой саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (38295, 'Саженец', 'Политый сортовой саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (38772, 'Саженец', 'Саженец сердце-древа', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (40230, 'Саженец', 'Саженец хамелеонового дерева', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (40522, 'Саженец', 'Саженец сальфирии', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41337, 'Саженец', 'Саженец златолиста', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41461, 'Семена', 'Семена ананаса', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41473, 'Семена', 'Пакет семян ананаса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41474, 'Семена', 'Семена фиалки', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41475, 'Семена', 'Пакет семян фиалки', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41476, 'Семена', 'Семена амаранта', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41477, 'Семена', 'Пакет семян амаранта', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41478, 'Саженец', 'Саженец гибискуса', 300);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41479, 'Саженец', 'Саженец крупнолистого гибискуса', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41480, 'Семена', 'Семена арбуза', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41481, 'Семена', 'Пакет семян арбуза', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41978, 'Семена', 'Семена бальзамина', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (41979, 'Семена', 'Пакет семян бальзамина', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42172, 'Семена', 'Качественные семена злаков', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42173, 'Семена', 'Качественные семена пряных трав', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42174, 'Семена', 'Качественные семена плодов', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42175, 'Семена', 'Качественные семена лекарственных трав', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42176, 'Семена', 'Качественные цветочные семена', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42260, 'Удобрение', 'Первосортный компост', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42748, 'Саженец', 'Пакет семян тыквенного батата', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (42857, 'Саженец', 'Политый сортовой саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (43071, 'Семена', 'Семена медузника', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (43409, 'Саженец', 'Саженец любвеобильной вишни', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (45672, 'Саженец', 'Саженец девичьей вишни', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (264570, 'Семена', 'Пакет зерен овса', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (302920, 'Семена', 'Пакет семян перца', 500);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (430708, 'Семена', 'Семена златоцвета', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (455093, 'Саженец', 'Саженец кроличьей вишни', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8000165, 'Саженец', 'Политый сортовой саженец акхиумного дерева', 800);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8000995, 'Детеныш', 'Ромашка', 1200);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8000996, 'Саженец', 'Призовая секвойя', 750);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8000997, 'Семена', 'Призовая рисовая делянка', 1200);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8001101, 'Саженец', 'Необычное синее семечко', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8001102, 'Саженец', 'Необычное красное семечко', 0);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (8002063, 'Семена', 'Семена сахарной кукурузы', 150);
INSERT INTO `seeds`(`item_id`, `category`, `item_name`, `cultisize`) VALUES (80002095, 'Саженец', 'Сортовой саженец акхиумного дерева', 800);
