INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (1, 'Фанем', 2);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (2, 'Нуи', 2);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (3, 'Шаеда', 2);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (4, 'Корвус', 1);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (5, 'Луций', 1);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (6, 'Каиль', 1);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (7, 'Ария', 1);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (8, 'Хазе', 2);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (9, 'Сервер ?', 2);
INSERT INTO `servers`(`id`, `server_name`, `server_group`) VALUES (10, 'Ренессанс', 4);
