INSERT INTO `slots`(`id`, `slot_name`) VALUES (1, 'Голова');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (2, 'Грудь');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (3, 'Пояс');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (4, 'Локти');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (5, 'Руки');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (6, 'Плащ');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (7, 'Попа');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (8, 'Ноги');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (9, 'Исподнее');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (10, 'Шея');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (11, 'Ухо');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (12, 'Ухо');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (13, 'Палец');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (14, 'Палец');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (15, 'Одна рука');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (16, 'Оружие левое');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (17, 'Лук');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (18, 'Инструмент');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (19, 'Глайдер');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (20, 'Костюм');
INSERT INTO `slots`(`id`, `slot_name`) VALUES (21, 'Обе руки');
