INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (1, 'База предметов предоставлена Archeagecodex.com');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (2, 'Для корректного расчета прибыли настройте уровни профессий.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (3, 'Чтобы настройки не пропадали выполните вход.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (4, 'Отметьте пользователей, чьим ценам можно доверять.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (5, 'Dllib.ru никогда не отправляет писем на почту.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (6, 'Вы можете выбрать режим видимости цен, чтобы исключить нелепые данные.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (7, 'Настройки доверия не влияют на предметы с субъективной ценой. ОР, РР, Честь итд будут предпочитаться ваши.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (8, 'При обычных настройках, если Вы не указывали цену, она будет найдена у кого-нибудь другого. И она может Вам не понравиться.:)');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (9, 'В профиле можно переключаться между аккаунтами.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (10, 'В игре ник \"Граф\" у меня только на сервере \"Шаеда\".');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (11, 'Стоимость отходов уже учтена в расчете рецепта.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (12, 'Наиболее корректно сайт отображается в Google Chrome 78.0 или выше.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (13, 'Калькулятор помнит рецепты, которые вы отметили, как основные.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (14, 'Если Вы не отметили рецепт, калькулятор выбирает его сам.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (15, 'При входе вы получаете случайный Ник. В профиле можно его изменить.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (16, 'Сиоль не влияет на паки за Растворы.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (17, 'Записи о предметах с субъективной ценой не отображаются в Сообществе.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (18, 'Чтобы отображаться в списке сообщества войдите на сайт и сделайте записи о ценах.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (19, 'Самый дешевый рецепт не обязательно самый эффективный.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (20, 'Калькулятор помнит предметы, которые вы покупаете, а не крафтите.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (21, 'Если не хотите, чтобы калькулятор выбирал рецепты с Векселем региональной общины, сделайте его дороже.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (22, 'Выбранными рецептами можно управлять в настройках.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (23, 'Калькулятор может помочь определить цену Ремесленной репутации или чести.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (24, 'Не забудьте указать сервер.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (25, 'Хранить настройки незарегистрированного пользователя затруднительно.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (26, 'Не пренебрегайте стоимостью ОР. Это эквивалент времени, а не ресурс.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (27, 'Цены аукционных групп изолированы друг от друга.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (28, 'Чаще всего странный результат расчёта детерминирован странными исходными данными.');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (29, 'Паки - наше всё! =)');
INSERT INTO `tiptops`(`tip_id`, `tip_text`) VALUES (30, 'Из режимов рекомендую \"Маргинал\".');
