INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (1, 'Лес Гвинедар', 1, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (2, 'Мэрианхольд', 1, 0, NULL, NULL, 2);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (3, 'Земля Говорящих Камней', 1, 0, NULL, NULL, 2);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (4, 'Полуостров Рассвета', 2, 1, NULL, 1, 1);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (5, 'Полуостров Солрид', 1, 1, 1, NULL, 1);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (6, 'Холмы Лилиот', 1, 0, NULL, NULL, 2);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (7, 'Радужные Пески', 2, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (8, 'Две Короны', 1, 1, 1, NULL, 1);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (9, 'Махадеби', 2, 0, NULL, NULL, 2);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (10, 'Иммергрунское Нагорье', 1, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (11, 'Плато Соколиной Охоты', 2, 0, NULL, NULL, 2);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (12, 'Поющая Земля', 2, 1, NULL, 1, 1);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (13, 'Морозная Гряда', 1, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (14, 'Багровый Каньон', 2, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (15, 'Руины Харихараллы', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (16, 'Рокочущие Перевалы', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (17, 'Инистра', 2, 1, NULL, 1, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (18, 'Белый Лес', 1, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (19, 'Кладбище Драконов', 1, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (20, 'П-oв Падающих Звезд', 1, 1, 1, NULL, 1);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (21, 'Долина Талых Снегов', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (22, 'Золотые Равнины', 1, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (23, 'Хазира', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (24, 'Тигриный Хребет', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (25, 'Древний Лес', 2, 0, NULL, NULL, 3);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (26, 'Заболоченные Низины', 1, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (27, 'Долгая Коса', 1, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (28, 'Долина Цветущих Прудов', 1, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (29, 'Саванна', 2, 0, NULL, NULL, 4);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (30, 'Остров Свободы', 9, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (31, 'Бездна', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (32, 'Земли Покоя', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (33, 'Нуимар', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (34, 'Сальфимар', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (35, 'Сангемар', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (36, 'Солнечные Поля', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (37, 'Сверкающее побережье', 3, 1, 1, 1, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (38, 'Замок Ош', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (39, 'Бухта Китобоев', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (40, 'Изначальный материк', 3, 0, NULL, NULL, NULL);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (50, 'Фактории Запада', 1, NULL, NULL, NULL, 5);
INSERT INTO `zones`(`zone_id`, `zone_name`, `side`, `is_get`, `get_west`, `get_east`, `fresh_type`) VALUES (51, 'Фактории Востока', 2, NULL, NULL, NULL, 5);
